# Generated by Django 3.1.7 on 2021-03-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='heading',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='post',
            name='pitch',
            field=models.FloatField(default=90.0),
        ),
    ]
